### ISSUE TITLE
Upgrade base image to latest alpine

### ISSUE THREAD

**Issue by gaby** [joseluisq/alpine-curl#1]
I noticed the image is using alpine 3.16.5, which only supports zstd 1.5.2

Upgrading to 3.17.3 will add support for zstd 1.5.5 which supports async decompression.

**Comment by joseluisq** [comment]
Sure, we can. PR welcome!

**Comment by gaby** [comment]
Sure, I can send a PR tomorrow. :-)

**Comment by gaby** [comment]
@joseluisq PR has been submitted. May be worth doing the same in the static-web-server repo
